# Generated by Django 4.2.1 on 2023-05-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_pic', models.ImageField(upload_to='temp/%Y/%m/input/')),
                ('change_pic', models.ImageField(upload_to='temp/%Y/%m/change/')),
            ],
        ),
    ]
