# Generated by Django 4.2.1 on 2023-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='change_pic',
            field=models.ImageField(null=True, upload_to='temp/%Y/%m/change/'),
        ),
    ]
