# Generated by Django 4.2.1 on 2023-05-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_process', '0002_alter_picture_change_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='change_pic',
            field=models.ImageField(null=True, upload_to='%Y/%m/change/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='input_pic',
            field=models.ImageField(upload_to='%Y/%m/input/'),
        ),
    ]
