# Generated by Django 4.2.1 on 2023-05-27 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_process", "0003_alter_picture_change_pic_alter_picture_input_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picture_set",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
